server.port=${SERVER_PORT}
spring.application.name=Customer Service
spring.data.mongodb.database=${DB_NAME}
spring.data.mongodb.uri=mongodb+srv://${DB_USER}:${DB_PASSWORD}@cluster0.cr37uol.mongodb.net/${DB_NAME}
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.intervention.topic-name=intervention-output-0
spring.kafka.producer.document.topic-name=document-output-0
spring.kafka.consumer.account.topic-name=account-input-0
spring.kafka.consumer.group-id=customer-consumer-group
spring.kafka.bootstrap-servers=localhost:29092